// CMUdict-based pronunciation lookup
// This is a representative subset of common English words and their IPA transcriptions.
// In production, replace with a full CMUdict database lookup.

const CMUDICT: Record<string, string[]> = {
  "the": ["ðə", "ði"],
  "a": ["ə", "eɪ"],
  "and": ["ænd", "ənd"],
  "of": ["əv", "ʌv"],
  "to": ["tə", "tuː"],
  "in": ["ɪn"],
  "is": ["ɪz"],
  "it": ["ɪt"],
  "that": ["ðæt", "ðət"],
  "for": ["fɔːr", "fər"],
  "on": ["ɒn", "ɑːn"],
  "are": ["ɑːr", "ər"],
  "as": ["æz", "əz"],
  "with": ["wɪð", "wɪθ"],
  "he": ["hiː"],
  "was": ["wɒz", "wəz"],
  "his": ["hɪz"],
  "they": ["ðeɪ"],
  "be": ["biː"],
  "at": ["æt"],
  "one": ["wʌn"],
  "have": ["hæv"],
  "this": ["ðɪs"],
  "from": ["frɒm", "frəm"],
  "or": ["ɔːr", "ər"],
  "an": ["æn", "ən"],
  "had": ["hæd"],
  "but": ["bʌt"],
  "not": ["nɒt", "nɑːt"],
  "what": ["wɒt", "wʌt"],
  "all": ["ɔːl"],
  "were": ["wɜːr", "wər"],
  "when": ["wɛn"],
  "we": ["wiː"],
  "there": ["ðɛr"],
  "can": ["kæn", "kən"],
  "so": ["soʊ"],
  "up": ["ʌp"],
  "out": ["aʊt"],
  "said": ["sɛd"],
  "about": ["əˈbaʊt"],
  "me": ["miː"],
  "its": ["ɪts"],
  "into": ["ˈɪntuː", "ˈɪntə"],
  "your": ["jɔːr", "jər"],
  "time": ["taɪm"],
  "go": ["ɡoʊ"],
  "no": ["noʊ"],
  "do": ["duː"],
  "how": ["haʊ"],
  "my": ["maɪ"],
  "people": ["ˈpiːpəl"],
  "make": ["meɪk"],
  "year": ["jɪr"],
  "know": ["noʊ"],
  "take": ["teɪk"],
  "think": ["θɪŋk"],
  "see": ["siː"],
  "world": ["wɜːrld"],
  "than": ["ðæn", "ðən"],
  "could": ["kʊd"],
  "way": ["weɪ"],
  "good": ["ɡʊd"],
  "day": ["deɪ"],
  "man": ["mæn"],
  "work": ["wɜːrk"],
  "come": ["kʌm"],
  "like": ["laɪk"],
  "more": ["mɔːr"],
  "use": ["juːz", "juːs"],
  "get": ["ɡɛt"],
  "well": ["wɛl"],
  "say": ["seɪ"],
  "long": ["lɒŋ", "lɔːŋ"],
  "new": ["njuː", "nuː"],
  "first": ["fɜːrst"],
  "last": ["læst", "lɑːst"],
  "large": ["lɑːrdʒ"],
  "little": ["ˈlɪtəl"],
  "very": ["ˈvɛri"],
  "after": ["ˈæftər"],
  "through": ["θruː"],
  "back": ["bæk"],
  "show": ["ʃoʊ"],
  "place": ["pleɪs"],
  "around": ["əˈraʊnd"],
  "only": ["ˈoʊnli"],
  "need": ["niːd"],
  "look": ["lʊk"],
  "help": ["hɛlp"],
  "try": ["traɪ"],
  "great": ["ɡreɪt"],
  "name": ["neɪm"],
  "speak": ["spiːk"],
  "right": ["raɪt"],
  "really": ["ˈriːəli"],
  "give": ["ɡɪv"],
  "just": ["dʒʌst"],
  "every": ["ˈɛvri"],
  "might": ["maɪt"],
  "should": ["ʃʊd"],
  "before": ["bɪˈfɔːr"],
  "here": ["hɪr"],
  "now": ["naʊ"],
  "hard": ["hɑːrd"],
  "even": ["ˈiːvən"],
  "both": ["boʊθ"],
  "life": ["laɪf"],
  "those": ["ðoʊz"],
  "American": ["əˈmɛrɪkən"],
  "English": ["ˈɪŋɡlɪʃ"],
  "pronunciation": ["prəˌnʌnsiˈeɪʃən"],
  "practice": ["ˈpræktɪs"],
  "language": ["ˈlæŋɡwɪdʒ"],
  "sound": ["saʊnd"],
  "accent": ["ˈæksənt"],
  "phoneme": ["ˈfoʊniːm"],
  "vowel": ["ˈvaʊəl"],
  "consonant": ["ˈkɒnsənənt"],
  "word": ["wɜːrd"],
  "sentence": ["ˈsɛntəns"],
  "phrase": ["freɪz"],
  "hello": ["həˈloʊ", "hɛˈloʊ"],
  "world": ["wɜːrld"],
  "beautiful": ["ˈbjuːtɪfəl"],
  "water": ["ˈwɔːtər", "ˈwɑːtər"],
  "butter": ["ˈbʌtər"],
  "bottle": ["ˈbɒtəl", "ˈbɑːtəl"],
  "mountain": ["ˈmaʊntɪn"],
  "button": ["ˈbʌtən"],
  "cotton": ["ˈkɒtən", "ˈkɑːtən"],
  "kitten": ["ˈkɪtən"],
  "three": ["θriː"],
  "thing": ["θɪŋ"],
};

export function lookupWord(word: string): { word: string; pronunciations: string[]; found: boolean } {
  const lower = word.toLowerCase().replace(/[^a-z']/g, "");
  const pronunciations = CMUDICT[lower];
  if (pronunciations && pronunciations.length > 0) {
    return { word, pronunciations, found: true };
  }
  return { word, pronunciations: [], found: false };
}

export function lookupText(text: string): Array<{ word: string; pronunciations: string[]; found: boolean }> {
  const words = text.trim().split(/\s+/).filter(Boolean);
  return words.map(lookupWord);
}
